### ISSUE TITLE
Add copy button

### ISSUE THREAD

**Issue by rugk** [webtorrent/instant.io#119]
You can just use https://github.com/zenorocha/clipboard.js/

**Comment by sg-s** [comment]
what do you want copied?

**Comment by rugk** [comment]
the URL, of course

**Comment by sg-s** [comment]
isn't that something you paste in? so you already have it on your clipboard...

**Comment by rugk** [comment]
Well…

1. A starts streaming.
2. A needs to get URL and copy it in some chat system to B.
3. B clicks link/copies it into the site.

So actually, the copy feature is needed for A. I doubt many people will share the URL by writing them off the screen, rather than using a chat service/instant messenger or similar.

**Comment by sg-s** [comment]
i see, that makes sense

meanwhile, you can also just copy the url -- and paste that directly into webtorrent desktop, and that works well

**Comment by styfle** [comment]
Alternative: https://copee.ceriously.com

**Comment by rugk** [comment]
Actually, AFAIK, it is a small js api anyway, so third party scripts are not really needed.

**Comment by feross** [comment]
Thanks for reporting this issue. Due to time constraints, I don't have any plans to work on this so I'm going to close it. If you would like to see it implemented, please send a pull request!

![mickey-wizard](https://user-images.githubusercontent.com/121766/62907205-e7fc7680-bd26-11e9-83f3-9614f069b5e0.gif)
