### ISSUE TITLE
Generate temporary short link for easier sharing

### ISSUE THREAD

**Issue by aswinmohanme** [webtorrent/instant.io#172]
I use this mainly for sharing files from my desktop to my mobile. The info hash is super long to type out, and currently I use firefox to send the data url to the phone.

I'm not aware of an easier way. Hence it would be pretty neat if temporary short links could be generated.

**Comment by feross** [comment]
I think this is a cool idea, but at the moment https://instant.io is a purely client-side application. Since it's meant to be a simple demo of WebTorrent usage, I think we should keep it simple for now. To implement short links, we'd need to add a DB to the backend.

At some point, I think we should put the current version of instant.io on demo.webtorrent.io and then expand the scope of instant.io to improve the UX and make it more user-friendly.

**Comment by aswinmohanme** [comment]
Maybe use the first few characters of the hash as the shortlink. It that possible ?
