### ISSUE TITLE
Subtitles support

### ISSUE THREAD

**Issue by whiver** [webtorrent/instant.io#179]
Hi team,
It would be really nice to have subtitle support, either providing a .srt/.vtt file or automatically downloading the associated subtitle if found.

Thanks!

**Comment by feross** [comment]
Thanks for reporting this issue. Due to time constraints, I don't have any plans to work on this so I'm going to close it. If you would like to see it implemented, please send a pull request!

![mickey-wizard](https://user-images.githubusercontent.com/121766/62907205-e7fc7680-bd26-11e9-83f3-9614f069b5e0.gif)
