### ISSUE TITLE
Add a note saying that this will only work with peers using instant.io ?

### ISSUE THREAD

**Issue by ganezdragon** [webtorrent/instant.io#188]
Could we add a note somewhere in the site, saying something like,

> Note: The site needs peers to be using instant.io to transfer the files.

or, if this sounds geeky, can someone think of something user friendly to say? We definitely want this information to be conveyed to the user, since from personal experience, I was puzzled the first time when I was using the site and found that there were no peers when redacted clearly told me that there were.

**Comment by jimmywarting** [comment]
It don't have to be peers that are using instant.io. Peers can come from other places too like webtorrent-desktop and other websites that also uses webtorrent

Some torrent clients are implementing webrtc also so they too can connect to browser peers and vise versa

Then it's also about discovery. A normal http tracker that tpb uses are not able to work in browsers, therefore a websocket tracker (wss) needs to be used instead.
a websocket tracker are fairly new and ain't that popular yet unfortunately, so a websocket tracker is not added into the magnet links or the torrent file that tpb provides.

So what webtorrent dose is adding a few trackers
```js
  [ 'wss://tracker.btorrent.xyz' ],
  [ 'wss://tracker.openwebtorrent.com' ],
  [ 'wss://tracker.fastcast.nz' ]
```

if peers don't use the same trackers then they can't discover other peers.

**Comment by ganezdragon** [comment]
@jimmywarting , do you mean instant.io can also use other usual torrent clients (like bittorrent) ? I know it could use clients with webrtc, or I atleast thought it only supports webrtc clients.

**Comment by jimmywarting** [comment]
> do you mean instant.io can also use other usual torrent clients

Yes

> like bittorrent

no, i don't think they have implemented webrtc. here is a list of some torrent clients and some progress https://github.com/webtorrent/webtorrent/issues/369

A more correct note would be

> "Note: The site can only connect to peers that talks webrtc and can only discover peer that are connected to a websocket tracker" like any hybrid client (for example webtorrent-desktop)

websocket is necessary since there is no DHT avalible in webtorrent's rtc protocol (at least yet), but it's also necessary for sdp offer/answer signaling to match two peer with eachother. it's not as simple as a ip:port. it's not possible to either reconnect with the same sdp offer/answer

once you have at least one connection only then are you able to discover new peer throught other peers

**Comment by ganezdragon** [comment]
It would be better if we add this Note in a more end-user understandable form. 😄 @jimmywarting, others, Can we add this to the site?

**Comment by feross** [comment]
Please send a PR with a suggested wording and we'll consider it. Thanks.
