### ISSUE TITLE
Instant.io keeps opening magnet link on chrome

### ISSUE THREAD

**Issue by ivex001** [webtorrent/instant.io#195]
I can make this site to stop opening magnet links. I've search here someone with exact same problem but he doesn't remember how to stop this. Please need to remove this and use my default program for magnet links.

Thanks

**Comment by Th3N3rdyGam3r** [comment]
I am having this exact same issue. I've tried editing the registry, changing preferences in windows, editing chrome configs, and more and can't get it to open in anything other than chrome. Even disabling the setting in chrome for magnet handling just make the links not work anymore.

**Comment by Th3N3rdyGam3r** [comment]
@ivex001 I was just having this same issue, but was somehow able to fix it. I'll tell you some of the things I did that MAY have helped fix it. I'm not sure exactly what did it in the end.

- Going into chrome://settings/handlers and removing instant.io from the magnet handler
- Going to https://instant.io/ and when it asks me if I want to allow it to open mangnet link, hit BLOCK/DENY
- Going to each of the following windows registry keys in regedit and changing the default key to, in my case, "C:\Program Files\qBittorrent\qbittorrent.exe" "%1"
```
Computer\HKEY_CURRENT_USER\Software\Classes\magnet\shell\open
Computer\HKEY_CLASSES_ROOT\magnet\shell\open\command
```
- Going to %LOCALAPPDATA%\Google\Chrome\User Data\[My Profile] searching for the last instance of "protocol_handler": and making sure "magnet":false was set in "excluded_schemes":{} while chrome is completely closed (This one seems least likely to have had any effect since I didn't really make any changes)

I did several of these steps many times, constantly tested a magnet link after restarting chrome, and constantly rechecked the registry keys for any changes. You may have to try a different combination or do it another time for something to pop up, but hopefully something here works for you too.

**Comment by ivex001** [comment]
@Th3N3rdyGam3r , yes i managed to fix it. I did discover the hrome://settings/handlers but after that no magnet link was opening. Than finally i found the reg trick. Thanks anyway

**Comment by feross** [comment]
You can tell Chrome to remove `instant.io` as your magnet link handler by visiting `chrome://settings/handlers`.

As for setting another app as your default magnet link handler, it will vary depending on which torrent app you're using.

**Comment by vrajeshkanna** [comment]
[This](https://www.linuxbabe.com/desktop-linux/how-to-change-the-default-torrent-program-on-linux) worked for me
