### ISSUE TITLE
Does it download the torrents locally?

### ISSUE THREAD

**Issue by htorbov** [webtorrent/instant.io#199]
This is just amazing. I basically can use any magnet link and it streams it on my browser. But does the script download the files locally, or it's just in the browser? Thanks!

**Comment by jimmywarting** [comment]
- It only download in to the browsers memory.
- Browser can't read/write to the filesystem.
- webtorrent (instant.io) could read/write to any of the browsers web storage, sandboxed filesystem, indexedDB or the new [kv storage](https://github.com/WICG/kv-storage) or any other [abstract chunk store](https://github.com/mafintosh/abstract-chunk-store) compatible storage but instant.io only use default mem storage
- you can always download all files as a zip when the download is complete by clicking on the link "Download all files as zip"
- unfortunately it is not as streamable right away since it has to download all files before it can zip everything with JSZip
  - this could be salvage if instant.io used [StreamSaver](https://github.com/jimmywarting/StreamSaver.js) with a combination of this two examples [download using webtorrent](https://jimmywarting.github.io/StreamSaver.js/examples/torrent.html) and [saving multiple files](https://jimmywarting.github.io/StreamSaver.js/examples/saving-multiple-files.html) with a [streamable zip interface](https://github.com/jimmywarting/StreamSaver.js/blob/master/examples/zip-stream.js) wish i built that not long ago. Then you can use instant.io to save something right away before any pieces has been downloaded. 

i know that @feross knew about StreamSaver before, but i guess he didn't use cuz it wasn't cross browser compatible since it relied on service worker and there where no way to save multiple files so he had to zip it using [JSZip](https://github.com/Stuk/jszip) once the zip file was competed and eaten up all memory and gave you a final zip blob back - could you use download link, 
hence why i built a new streamable zip generator instead and made a fallback solution that don't require service worker for legency browsers

**Comment by bystefu** [comment]
Can stream file before download is finished 100%?
