### ISSUE TITLE
Research facilitating preview (rich) cards with link sharing #Question #Suggestion

### ISSUE THREAD

**Issue by ldexterldesign** [webtorrent/instant.io#205]
**What version of this package are you using?**

Version 0.20.0 (0.99.3)

**What problem do you want to solve?**

As a user when I share links (e.g. [m]astodon, twitter) I want preview (rich) cards (inc. player widgets for audio/video)

**What do you think is the correct solution to this problem??**

I assume this functionality is controlled destination-side (i.e. Mastodon, Twitter) but if I'm wrong or WebTorrent can add some meta (source-side) to help facilitate this then we should do that?

**Are you willing to submit a pull request to implement this change?**

Willing, yes. (Technically) able, possibly (I know some HTML/CSS/JS).

Hope to hear back

Thanks for wonderful software and keep up great work!

Cheers

m: https://github.com/tootsuite/mastodon/issues/6992

**Comment by feross** [comment]
These services get the preview metadata from HTML tags (https://ogp.me/ and https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/markup.html) but these must be returned in the server response so it is part of the HTML.

However, since instant.io just serves the same simple HTML to everyone and relies on the client's browser to download the files, the server can't (and shouldn't) know anything about is being downloaded.

We could hard-code in some generic image, but it is not possible to make it based on the content being shared.

**Comment by ldexterldesign** [comment]
Thanks for reply and clarification

Could we do something with magnet URI [k]eywords?

Yours hopefully

k: https://en.wikipedia.org/wiki/Magnet_URI_scheme#Keywords_(kt)

**Comment by feross** [comment]
Everything after the hash (`#`) in the URL is not sent to the server, so when the user visits `https://instant.io/#<magnet-url-here>` for example, the server just sees a request for `https://instant.io/`

So there's no way for the server to read the keyword out of the magnet url.

**Comment by ldexterldesign** [comment]
> Everything after the hash (#) in the URL is not sent to the server

Is this a design decision?:

* If yes then what's the reason
* If no then would you be accept the addition of keyword parsing to help solve this use case

Yours hopefully

**Comment by ldexterldesign** [comment]
Also, hypothetically, if we put some OGP meta on an instant.io page (technically) how would the likes of twitter.com treat it?:

```
<meta property="og:title" content="[artist] - [track].mp3" />
<meta property="og:type" content="audio" />
<meta property="og:url" content="[instant.io page]" />
<meta property="og:image" content="cover.jpg" />
```

**Comment by feross** [comment]
> If yes then what's the reason (if you don't mind me asking)

We don't want the server to see what the user is downloading. We want the server to just serve a plain html file to the user's browser and have all the magic happen there.

> if we put some OGP meta on an instant.io page (technically) how would the likes of twitter.com treat it?

We can't put an OGP meta tags on the page that are based on the torrent the user is downloading since the server can't see the torrent ID.

> This would be an insanely cool way for users to share media content on social networks without uploading media content to social networks

This is a neat idea. But I can't think of how to get it to work with the current architecture. You could fork instant.io and make your own site where you send the infohash to the server by changing `#` to `?id=` or something. But we can't do that on instant.io.
